function [fitresult, gof] = createFit(xx, cv2)
%CREATEFIT(XX,CV2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: cv2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Apr-2013 11:26:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xx, cv2 );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.459446364031729 231 7.36584630157225 0.450804943214983 523 7.4199159491682 0.42138507499105 133 10.43824423232 0.378368913827765 426 8.02060172790559 0.371169421218897 36 16.9462677528558 0.366164362474159 328 9.43438490485887 0.349395130378355 620 10.4491764117581 0.336688494925726 717 16.0382160729401];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




