function [fitresult, gof] = createFit(xx, cv2)
%CREATEFIT(XX,CV2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: cv2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Sep-2014 09:37:02


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xx, cv2 );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.365262850255504 42 6.3102568144296 0.341201641096731 140 9.08438782851892];
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cv2 vs. xx', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'xx' );
ylabel( 'cv2' );
grid on


