function [fitresult, gof] = createFit(yy2, cv_2)
%CREATEFIT(YY2,CV_2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : yy2
%      Y Output: cv_2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Sep-2014 10:37:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( yy2, cv_2 );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.31874154271542 134 8.25937798633846 0.309687763842179 36 5.85488775890496];
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cv_2 vs. yy2', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'yy2' );
ylabel( 'cv_2' );
grid on


