function [fitresult, gof] = createFit(yy, cv2)
%CREATEFIT(YY,CV2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : yy
%      Y Output: cv2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Apr-2013 11:30:32


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( yy, cv2 );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [0.388281891003671 104 10.8885920073554];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );