function [fitresult, gof] = createFit(x2, cv2)
%CREATEFIT(X2,CV2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x2
%      Y Output: cv2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Feb-2015 11:51:52


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x2, cv2 );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.00292703377319969 1029 7.58385590600864 0.00265695933059928 1127 7.5644558743933 0.00253758373746005 931 11.2960367062378 0.00246319060255185 1223 9.2449975516908 0.00245804521531068 834 16.7143422771947 0.00185333328004955 1321 9.3228304701838 0.00114631256102404 1416 13.2850400559795 0.000898947729390254 1512 20.4995125767817];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'cv2 vs. x2', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'x2' );
% ylabel( 'cv2' );
% grid on


