function [fitresult, gof] = createFit(y2, ch2)
%CREATEFIT(Y2,CH2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : y2
%      Y Output: ch2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Feb-2015 12:27:43


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( y2, ch2 );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.00314042419963312 754 6.84660983447242 0.00311805199649506 852 7.436726038262 0.00281422497507 657 8.98845628829239 0.00246198933248909 559 12.6231582777952 0.00244115807203571 462 17.8831257039672 0.00239488135389343 950 8.97007195525102 0.0022003695733287 1046 12.2072504554914 0.00138122779755323 1143 20.0955112981303];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'ch2 vs. y2', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'y2' );
% ylabel( 'ch2' );
% grid on


