function [fitresult, gof] = createFit(x, cv)
%CREATEFIT(X,CV)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: cv
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Feb-2015 12:04:20


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, cv );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.00299698999830211 541 6.64619252580594 0.00277773261895631 443 7.62644733595728 0.00275971703939248 639 8.67314985472201 0.00247210847820989 736 11.730361719679 0.00245804521531068 834 16.4660890976234 0.00204272886860946 346 9.06131178204011 0.0015167323443751 249 12.6623627296701 0.000899216329140473 153 21.1613330806312];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'cv vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'x' );
% ylabel( 'cv' );
% grid on


